---
# tasks file for netzwirt.git-server


- name: install git
  apt:
    name: git
    state: present


- name: add git-shell to /etc/shells
  lineinfile:
    dest: /etc/shells
    line: /usr/bin/git-shell


- name: add git user
  user:
    name: git
    state: present
    shell: /usr/bin/git-shell


- name: create git-shell-commands directory
  file:
    name: /home/git/git-shell-commands
    state: directory 
    mode: 0755
    owner: git
    group: git


- name: create no-interactive-login
  template:
    dest: /home/git/git-shell-commands/no-interactive-login
    src: no-interactive-login.j2
    mode: 0755
    owner: git
    group: git


- name: manage public keys
  authorized_key:
    user: git
    key: "{{ lookup('file', git_server_lookup_keys + '/' + item + '.pub') }}"
  with_items:
    - "{{git_server_user_keys}}"


- name: init repositories path
  file:
    name: /home/git/repo
    state: directory 
    mode: 0755
    owner: git
    group: git


- name: create repositories path
  file:
    name: /home/git/repos/{{item}}.git
    state: directory 
    mode: 0755
    owner: git
    group: git
  with_items:
    - "{{git_server_repos}}"
    
    
- name: init repositories
  become_user: git
  command: git init --bare
  args:
    chdir: "/home/git/repos/{{item}}.git"
    creates: "/home/git/repos/{{item}}.git/HEAD"
  with_items:
    - "{{git_server_repos}}"

    
    
