---
# tasks file for netzwirt.git-server


- name: install git on debian-like system
  apt:
    name: git
    state: present


- name: add git-shell to /etc/shells
  lineinfile:
    dest: /etc/shells
    line: /usr/bin/git-shell


- name: add git user
  user:
    name: git
    state: present
    shell: /usr/bin/git-shell


- name: create git-shell-commands directory
  file:
    name: /home/git/git-shell-commands
    state: directory 
    mode: 0755
    owner: git
    group: git


- name: create no-interactive-login
  template:
    dest: /home/git/git-shell-commands/no-interactive-login
    src: no-interactive-login.j2
    mode: 0755
    owner: git
    group: git


- name: manage public keys
  authorized_key:
    user:  git
    state: present
    key: "{{ git_server_ssh_keys|join(\"\n\") }}"
    exclusive: True
  tags:
  - manage-keys


- name: init repositories path
  file:
    name: /home/git/repos
    state: directory
    mode: 0755
    owner: git
    group: git


- name: create repositories path
  file:
    name: /home/git/repos/{{item}}.git
    state: directory
    mode: 0755
    owner: git
    group: git
  with_items:
    - "{{git_server_repos}}"


- name: init repositories
  become_user: git
  command: git init --bare --shared
  args:
    chdir: "/home/git/repos/{{item}}.git"
    creates: "/home/git/repos/{{item}}.git/HEAD"
  with_items:
    - "{{git_server_repos}}"


